/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Skull(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/human_skull/skull.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="g">
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group name="g001">
              <mesh
                name="defaultMaterial001"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial001.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group name="g002" />
            <group name="g003">
              <mesh
                name="defaultMaterial003"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial003.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/human_skull/skull.glb')
